"""empty message

Revision ID: 184dd3eff310
Revises: 422cb51eed2f
Create Date: 2019-04-16 11:18:36.049019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184dd3eff310'
down_revision = '422cb51eed2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
