"""empty message

Revision ID: 3f11a9c4f1e2
Revises: 7f1bc947993f
Create Date: 2019-05-01 15:27:20.629501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f11a9c4f1e2'
down_revision = '7f1bc947993f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('catalog', sa.Column('archive', sa.Boolean(), nullable=True))
    op.add_column('catalog', sa.Column('collection', sa.Boolean(), nullable=True))
    op.add_column('catalog', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('catalog', sa.Column('number', sa.String(length=250), nullable=True))
    op.add_column('catalog', sa.Column('publish_a', sa.Boolean(), nullable=True))
    op.add_column('catalog', sa.Column('publish_r', sa.Boolean(), nullable=True))
    op.add_column('catalog', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('catalog', sa.Column('status', sa.String(length=250), nullable=True))
    op.add_column('catalog', sa.Column('status2', sa.String(length=250), nullable=True))
    op.add_column('catalog', sa.Column('title', sa.String(length=250), nullable=True))
    op.add_column('catalog', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog', 'updated')
    op.drop_column('catalog', 'title')
    op.drop_column('catalog', 'status2')
    op.drop_column('catalog', 'status')
    op.drop_column('catalog', 'published')
    op.drop_column('catalog', 'publish_r')
    op.drop_column('catalog', 'publish_a')
    op.drop_column('catalog', 'number')
    op.drop_column('catalog', 'created')
    op.drop_column('catalog', 'collection')
    op.drop_column('catalog', 'archive')
    op.drop_table('meta')
    # ### end Alembic commands ###
