"""empty message

Revision ID: 46c8f054a7be
Revises: 6f2ba2c1cd62
Create Date: 2019-04-16 11:15:07.570877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c8f054a7be'
down_revision = '6f2ba2c1cd62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###
