"""empty message

Revision ID: 7f1bc947993f
Revises: 184dd3eff310
Create Date: 2019-04-16 11:42:38.787022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1bc947993f'
down_revision = '184dd3eff310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('given_name', sa.String(length=250), nullable=True),
    sa.Column('family_name', sa.String(length=250), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_foreign_key(None, 'catalog', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalog', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
